export const TIMELINE_STEPS = {
  TICKET_CREATED: "TICKET_CREATED",
  PACKAGE_RECEIVED: "PACKAGE_RECEIVED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  NOT_YET_SHIPPED: "NOT_YET_SHIPPED",
  AVAILABLE_FOR_PICKUP: "AVAILABLE_FOR_PICKUP",
  WAITING_FOR_CUSTOMER_ACTION: "WAITING_FOR_CUSTOMER_ACTION",
  DELIVERED_TO_SENDER: "DELIVERED_TO_SENDER",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERY_FAILED: "DELIVERY_FAILED",
};

export const TIMELINE_STEPS_ORDER = {
  [TIMELINE_STEPS.TICKET_CREATED]: 0,
  [TIMELINE_STEPS.PACKAGE_RECEIVED]: 1,
  [TIMELINE_STEPS.OUT_FOR_DELIVERY]: 2,
  [TIMELINE_STEPS.NOT_YET_SHIPPED]: 2,
  [TIMELINE_STEPS.CANCELLED]: 2,
  [TIMELINE_STEPS.DELIVERED_TO_SENDER]: 2,
  [TIMELINE_STEPS.DELIVERY_FAILED]: 2,
  [TIMELINE_STEPS.AVAILABLE_FOR_PICKUP]: 2,
  [TIMELINE_STEPS.WAITING_FOR_CUSTOMER_ACTION]: 2,
  [TIMELINE_STEPS.IN_TRANSIT]: 2,
  [TIMELINE_STEPS.DELIVERED]: 3,
};
